version = 0.1
[default.deploy.parameters]
stack_name = "resource-manager-api"
resolve_s3 = true
s3_prefix = "resource-manager-api"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
